# If you update this file, please also update _config.yml with the exact same changes
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
remote_theme: Orange-OpenSource/ods-jekyll-theme
defaults:
  - scope:
      path: ""
    values:
      version: ""
  - scope:
      path: "0.10.0"
    values:
      version: "0.10.0"
  - scope:
      path: "0.11.0"
    values:
      version: "0.11.0"
  - scope:
      path: "0.11.1"
    values:
      version: "0.11.1"
