plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
remote_theme: Orange-OpenSource/ods-jekyll-theme
defaults:
  - scope:
      path: ""
    values:
      version: ""
