name: android build

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build lib and sample app
        run: bash ./gradlew assemble --stacktrace
      
      - name: Store sample app
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: sample/build/outputs/apk/debug/sample-debug.apk
