name: android build

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Android Linter
        run: ./gradlew lintDebug

      - name: Build lib and sample app
        run: ./gradlew assemble --stacktrace

      - name: Store library
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: lib/build/outputs/aar/*.aar

      - name: Store sample app
        uses: actions/upload-artifact@v2
        with:
          name: sample
          path: catalog/build/outputs/apk/debug/*.apk
