name: android build

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Android Linter
        run: ./gradlew lintDebug

      - name: Build lib and sample app
        run: ./gradlew assemble --stacktrace

      - name: Store library
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: lib/build/outputs/aar/*.aar

      - name: Store sample app
        uses: actions/upload-artifact@v2
        with:
          name: sample
          path: catalog/build/outputs/apk/debug/*.apk

      - name: Upload demo artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: ods-demo-android
          file: demo/build/outputs/apk/debug/demo-debug.apk