name: deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Assemble lib and sample app
        run: ./gradlew assembleRelease --stacktrace

      - name: Store library
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: lib/build/outputs/aar/*.aar

      - name: Store sample app
        uses: actions/upload-artifact@v2
        with:
          name: sample
          path: sample/build/outputs/apk/**/*.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: catalog/build/outputs/apk/release/catalog-debug.apk

